#!/usr/bin/env bash
set -e

checkout() {
  [ -d "$2" ] || git clone "$1" "$2"
}

echo "Checking out dotfiles..."
checkout "git://github.com/dpcavalcanti/dotfiles.git" "$HOME/.dotfiles"

echo "Creating useful directories..."
mkdir -p ${HOME}/bin
mkdir -p ${HOME}/Applications
mkdir -p ${HOME}/Developer
mkdir -p ${HOME}/.ssh

#Install powerline Fonts
scripts/fonts.sh

#Install Homebrew
scripts/brew.sh


# TODO: Need change to iterm directory with its own script
#Configure default settings
#Configure git default settings
#Configure iterm
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm/config"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

if [ -f ${HOME}/.bash_profile ]; then
  grep "source $HOME/.dotfiles/bash_profile.bash" ${HOME}/.bash_profile || echo "source $HOME/.dotfiles/bash_profile.bash" >> $HOME/.bash_profile
else
  ln -s $HOME/.dotfiles/bash_profile.bash $HOME/.bash_profile
fi

if [ -f $HOME/.bashrc ]; then
  echo "source $HOME/.dotfiles/bashrc.bash" >> $HOME/.bashrc
else
  ln -s $HOME/.dotfiles/bashrc.bash $HOME/.bashrc
fi

